---
title: "2eme analyse"
author: "Savannah LAURENT"
date: "07/05/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Je n'ai pas réussi mais j'ai tout de même tenté.

```{r}
library(sf)
zone <- st_read("vote.gpkg", "zone")
str(zone)
zone$numBureau
zone [zone$numBureau == 1,]
zone [1,2]
plot(zone$geom)
fusion <- st_union(zone)
str(zone)
library(mapsf)
mf_map(zone, type = "choro", border = NA,var = "aire")
data <- read.csv("bondyElection.csv", fileEncoding = "UTF-8", dec = ",")
zone$Layer
data$Bureau.de.vote
dataSel <- data [c(1:32),]
zone$cle <- substring (zone$Layer,9,11)
dataSel$cle <- substring(dataSel$Bureau.de.vote, 3,5 )
dataSel$cle <- as.integer(dataSel$cle)
zone$cle <- as.integer(zone$cle)
length(zone$cle) == length(data$cle)
jointure <- merge(zone, dataSel, by = "cle")
st_write(jointure, "vote.gpkg", "jointure", delete_layer = T)
library(sf)
library(mapsf)
jointure <- st_read("vote.gpkg", "jointure", quiet = T)
names(jointure)
library(sf)
library(mapsf)
vote <- st_read("vote.gpkg", "jointure")
insee <- st_read("insee.gpkg", "bondy")
names(vote)[c(3,14)] <- c("bureau", "vote")
vote <- vote [, c("bureau", "vote")]
insee$densite <- (insee$Men_pauv / insee$Men)*100
insee <- insee [, "densite"]
hist(insee$densite, main = "densité des ménages pauvres")
inter <- st_intersection(vote, insee)
summary(inter)
inter <- st_cast(inter, "POLYGON")
mf_export(inter, filename ="propchoroF.png", width = 1000, res = 200, expandBB = c(0,0,0,0.6))
mf_map(inter, col = "orange", border = "antiquewhite1")
mf_map(inter, type ="prop_choro", var = c("vote", "densite"), leg_pos = c("topright", "right"))
mf_layout("Euh...", credits = "INSEE / PV Electoral\nBondy, avril 2022")
dev.off()
st_area(inter)
st_area(insee)
insee$aireTot <- st_area(insee)
inter <- st_intersection(vote, insee)
inter$nbRel <- (inter$densite * (st_area(inter)/ inter$aireTot) )
hist(inter$nbRel, main = "densité des ménages pauvres relatif à la taille des carreaux", xlab = "valeur de la densité", ylab = "nb d'occurence")
agg <- aggregate (inter$nbRel , by = list(inter$bureau), sum )
agg
names(agg) <- c("bureau", "densite")
names(vote)
jointure$densite
jointure$densite <- drop(jointure$densite)
mf_export(inter, filename ="propchoroT.png", width = 1000, res = 200, expandBB = c(0,0,0,0.8))
mf_map(jointure, type ="base", var = c("vote", "densite"), border = NA, leg_pos = c("topright", "right"), leg_title = c("vote (nb)", "densité\npauvres (%)"))
mf_layout(title = "Les précaires votent à gauche")
dev.off()
```

